# -*- coding: utf-8 -*-
"""MOVIES_RECOMMENDATION_SYSTEM(MAIN).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Monika9671/movie-recommendation-system/blob/main/MOVIES_RECOMMENDATION_SYSTEM(MAIN).ipynb

**Step 1: Upload files**
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir())

"""**Unzip files**"""

import zipfile

with zipfile.ZipFile("tmdb_5000_movies.csv.zip", 'r') as zip_ref:
    zip_ref.extractall()

with zipfile.ZipFile("tmdb_5000_credits.csv.zip", 'r') as zip_ref:
    zip_ref.extractall()

"""**Load in code**"""

import pandas as pd

movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

"""**Importing Required Libraries**"""

import pandas as pd
import numpy as np
import ast
import pickle
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors
from sklearn.decomposition import TruncatedSVD

"""**Loading and Merging Dataset**"""

movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

movies = movies.merge(credits, on='title')
movies.head()

"""**Selecting important columns (title, overview, genres, keywords, cast) required for building the recommendation system.**"""

movies = movies[['title','overview','genres','keywords','cast']]
movies.head()

"""**Checking missing values**"""

movies.isnull().sum()

"""**Removing Missing Values**"""

movies.dropna(inplace=True)

"""**Verification of Missing Values**"""

movies.isnull().sum()

"""**Checking for Duplicate Values**"""

movies.duplicated().sum()

"""**Removing Duplicate Values**"""

movies.drop_duplicates(inplace=True)

"""**Dataset Shape**"""

movies.shape

"""**Understanding the Genres Column**"""

movies['genres'].iloc[0]

"""**Converting JSON Data into Readable Format**"""

import ast

def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return " ".join(L)

"""**Applying Conversion to Genres Column**"""

movies['genres'] = movies['genres'].apply(convert)
movies[['title','genres']].head()

"""**Applying Conversion to Keywords Column**"""

movies['keywords'] = movies['keywords'].apply(convert)
movies[['title','keywords']].head()

"""**Applying Conversion to Cast Column**"""

movies['cast'] = movies['cast'].apply(convert)
movies[['title','cast']].head()

"""**Converting Cast Column into Text Format**"""

def convert_cast(text):
    L = []
    counter = 0

    try:
        for i in ast.literal_eval(text):
            if counter < 3:
                L.append(i['name'])
                counter += 1
            else:
                break
        return " ".join(L)

    except:
        return ""

"""**Displaying Cleaned Cast Data**"""

movies[['cast']].head()

"""**Displaying Processed Features**"""

movies[['overview','genres','keywords','cast']].head()

"""**Handling Missing Values in Overview**"""

movies['overview'] = movies['overview'].fillna('')

"""**Converting Text to Lowercase**"""

movies['overview'] = movies['overview'].apply(lambda x: x.lower())

"""**Creating Tags Column**"""

movies['tags'] = movies['overview'] + " " + movies['genres'] + " " + movies['keywords'] + " " + movies['cast']

"""**Displaying Title and Tags**"""

movies[['title','tags']].head()

"""**Cleaning Tags Column**"""

movies['tags'] = movies['tags'].apply(lambda x: " ".join(x.split()))

movies['tags'] = movies['tags'].apply(lambda x: x.lower())
movies[['tags']].iloc[0]

"""**Removing Punctuation from Tags**"""

import re

def remove_punc(text):
    return re.sub(r'[^a-zA-Z0-9\s]', '', text)

movies['tags'] = movies['tags'].apply(remove_punc)

"""**Applying Stemming to Tags**"""

from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

def stem(text):
    return " ".join([ps.stem(word) for word in text.split()])

movies['tags'] = movies['tags'].apply(stem)

"""**Removing Stopwords from Tags**"""

from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

def remove_stopwords(text):
    return " ".join([word for word in text.split() if word not in ENGLISH_STOP_WORDS])

movies['tags'] = movies['tags'].apply(remove_stopwords)

"""**Displaying Final Processed Tags**"""

movies['tags'].iloc[0]

"""**Importing TF-IDF Vectorizer**"""

from sklearn.feature_extraction.text import TfidfVectorizer

movies['tags'].iloc[0]

"""**Initializing TF-IDF Vectorizer**"""

tfidf = TfidfVectorizer(max_features=5000, stop_words='english')

"""**Applying TF-IDF Vectorization**"""

vectors = tfidf.fit_transform(movies['tags']).toarray()

vectors.shape

"""**Displaying Feature Names and Vector Values**"""

vectors[0][:20]
tfidf.get_feature_names_out()[:20]

"""**Importing Cosine Similarity**"""

import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

movies_data = pd.read_csv('/content/tmdb_5000_movies.csv')
print(movies_data.head())

print(movies_data.shape)

selected_features = ['genres', 'keywords', 'tagline', 'cast', 'director']
print(selected_features)

print(movies_data.columns)

selected_features = ['genres', 'keywords', 'tagline', 'overview']

for feature in selected_features:
    movies_data[feature] = movies_data[feature].fillna('')

combined_features = (
    movies_data['genres'] + ' ' +
    movies_data['keywords'] + ' ' +
    movies_data['tagline'] + ' ' +
    movies_data['overview']
)

print(combined_features)

vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)

print(feature_vectors)

similarity = cosine_similarity(feature_vectors)

print(similarity)

print(similarity.shape)

"""**Displaying Cosine Similarity Values**"""

similarity[0][:10]

"""**Enumerating Similarity Scores**"""

list(enumerate(similarity[0]))[:5]

"""**Importing Required Libraries for Machine Learning**"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

"""**Selecting Features and Target Variable**"""

X = movies_data.select_dtypes(include=['int64', 'float64'])
y = movies_data['revenue']

"""**Splitting Data into Training and Testing Sets**"""

import pandas as pd
from sklearn.model_selection import train_test_split

X = movies_data.select_dtypes(
    include=['int64', 'float64']
).fillna(0)

y = movies_data['revenue']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""**Checking Data Types of Training Features**"""

print(X_train.dtypes)

"""**Handling Missing Values by Removing Rows**"""

X = X.dropna()
y = y[X.index]

"""**Handling Missing Values using SimpleImputer**"""

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)

"""**Initializing Decision Tree Regressor with Controlled Depth**"""

from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor(max_depth=5)

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, max_depth=10)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""**Training and Predicting using Decision Tree Regressor**"""

from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor()
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("MSE:", mean_squared_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

"""**Importing and Initializing Random Forest Regressor**"""

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

"""**Initializing Random Forest Regressor with Hyperparameters**"""

model = RandomForestRegressor(
    n_estimators=100,
    max_depth=10,
    random_state=42
)

"""**Training Random Forest Model and Extracting Feature Importance**"""

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

importance = model.feature_importances_

pred = model.predict(X_test)

print("MSE:", mean_squared_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

"""**Importing Libraries for K-Nearest Neighbors (KNN) Model**"""

from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

"""**Applying Feature Scaling to the Entire Dataset**"""

scaler = StandardScaler()
X = scaler.fit_transform(X)

"""**Training and Predicting using K-Nearest Neighbors (KNN)**"""

model = KNeighborsRegressor(n_neighbors=5)
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("MSE:", mean_squared_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

"""**Hyperparameter Tuning using GridSearchCV**"""

from sklearn.model_selection import GridSearchCV

params = {
    'n_estimators': [50, 100],
    'max_depth': [5, 10]
}

grid = GridSearchCV(RandomForestRegressor(), params, cv=3)
grid.fit(X_train, y_train)

print(grid.best_params_)

"""**Evaluating Model using Cross-Validation**"""

from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=5)
print(scores.mean())

"""**Creating a DataFrame for Actual and Predicted Values**"""

results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": pred
})

print(results.head())

"""**Saving and Loading the Machine Learning Model**"""

import pickle

pickle.dump(model, open("model.pkl", "wb"))

model = pickle.load(open("model.pkl", "rb"))

"""**Visualizing Actual vs Predicted Values**"""

import matplotlib.pyplot as plt

plt.scatter(y_test, pred)
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.show()

"""**Calculating Feature Importance using Permutation Importance**"""

from sklearn.inspection import permutation_importance

result = permutation_importance(model, X_test, y_test)

importance = result.importances_mean

"""**Importing Libraries**"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor


from sklearn.preprocessing import StandardScaler

"""**Defining Features and Target Variable**"""

X = movies_data.select_dtypes(include=['int64', 'float64'])
y = movies_data['revenue']

"""**Handling Missing Values in Features and Target Variable**"""

X = X.fillna(X.mean())
y = y.fillna(y.mean())

"""**Splitting Data into Training and Testing Sets**"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""**Feature Scaling using StandardScaler**"""

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""**Defining Machine Learning Models**"""

models = {
    "Decision Tree": DecisionTreeRegressor(max_depth=5),
    "Random Forest": RandomForestRegressor(n_estimators=100, max_depth=10),
    "KNN": KNeighborsRegressor(n_neighbors=5),

}

"""**Training and Evaluating Multiple Machine Learning Models**"""

results = []

for name, model in models.items():

    if name in ["KNN", "SVR"]:
        model.fit(X_train_scaled, y_train)
        pred = model.predict(X_test_scaled)
    else:
        model.fit(X_train, y_train)
        pred = model.predict(X_test)

    mse = mean_squared_error(y_test, pred)
    r2 = r2_score(y_test, pred)

    results.append([name, mse, r2])

results_df = pd.DataFrame(results, columns=["Model", "MSE", "R2 Score"])
print(results_df)

"""**Visualizing Model Comparison using Bar Chart**"""

import matplotlib.pyplot as plt

plt.bar(results_df["Model"], results_df["R2 Score"])
plt.xticks(rotation=30)
plt.ylabel("R2 Score")
plt.title("Model Comparison")
plt.show()

"""**Selecting the Best Performing Model**"""

best_model = results_df.sort_values(by="R2 Score", ascending=False).iloc[0]
print(best_model)

"""**Training and Saving the Best Model**"""

import pickle

best_rf = RandomForestRegressor(n_estimators=100, max_depth=10)
best_rf.fit(X_train, y_train)

pickle.dump(best_rf, open("best_model.pkl", "wb"))

"""**Displaying Top 5 Movies Based on Predicted Score**"""

movies.columns

print(movies_data.shape)
print(similarity.shape)

movies_data['prediction'] = similarity.sum(axis=1)

print(movies_data.columns)

movies_data.sort_values(by="prediction", ascending=False)

model.fit(X_train.values, y_train)

predictions = model.predict(X.values)

print(predictions)

"""**Content-Based Recommendation Function**"""

def recommend(movie):
    index = movies[movies['title'] == movie].index[0]
    distances = similarity[index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )

    for i in movies_list[1:6]:
        print(movies.iloc[i[0]].title)

"""**Displaying Unique Genres using Set**"""

genres_list = movies_data['genres'].tolist()

genres_list = []

for genre in movies_data['genres']:
    genres_list.extend(str(genre).split())

print(set(genres_list))

"""**Displaying Unique Sorted Genres**"""

print(sorted(set(genres_list)))

"""**Counting Genre Frequency**"""

from collections import Counter

genre_count = Counter(genres_list)
print(genre_count)

"""**Creating Genre DataFrame**"""

genre_df = pd.DataFrame({
    "Genre": list(set(genres_list))
})

print(genre_df.sort_values(by="Genre"))

"""**Extracting and Cleaning Genre Information**"""

import ast

def extract_genres(obj):
    return [i['name'] for i in ast.literal_eval(obj)]

movies_data['genres_clean'] = movies_data['genres'].apply(extract_genres)

print(movies_data[['title', 'genres_clean']].head())

movies_data['genres_clean'] = movies_data['genres'].apply(extract_genres)

import ast

def extract_genres(obj):
    return [i['name'] for i in ast.literal_eval(obj)]

movies_data['genres_clean'] = movies_data['genres'].apply(extract_genres)

# get all genres
all_genres = sum(movies_data['genres_clean'], [])

print(sorted(set(all_genres)))

"""**Basic Genre-Based Recommendation Function**"""

def recommend_by_genre(genre, top_n=5):

    filtered = data[data['genres_clean'].apply(lambda x: genre in x)]

    filtered = filtered.sort_values(by='popularity', ascending=False)

    return filtered[['title', 'genres_clean', 'popularity']].head(top_n)

"""**Final Output of Genre-Based Recommendation System**"""

filtered = movies_data[movies_data['genres_clean'].apply(lambda x: genre in x)]

"""**Improved Genre-Based Recommendation Function**"""

def recommend_by_genre(genre, top_n=5):

    genre = genre.lower()

    filtered = data[data['genres_clean'].apply(
        lambda x: any(genre == g.lower() for g in x)
    )]

    filtered = filtered.sort_values(by='popularity', ascending=False)

    return filtered[['title', 'genres_clean', 'popularity']].head(top_n)

"""**Multi-Genre Recommendation using Flexible Matching**"""

def recommend_multiple_genres(genres, top_n=5):
    genres = [g.lower() for g in genres]

    filtered = movies_data[
        movies_data['genres_clean'].apply(
            lambda x: any(
                g.lower() in [i.lower() for i in x]
                for g in genres
            )
        )
    ]

    filtered = filtered.sort_values(
        by='popularity',
        ascending=False
    )

    return filtered[['title', 'genres_clean', 'popularity']].head(top_n)

"""**Displaying Multi-Genre Recommendation Output**"""

recommend_multiple_genres(["Fantasy", "Adventure"])

"""**Implementation of Genre-Based Recommendation Function**"""

def recommend_by_genre(genre, top_n=5):

    filtered = data[data['genres_clean'].apply(lambda x: genre in x)]

    filtered = filtered.sort_values(by=['vote_average', 'popularity'], ascending=False)

    return filtered[['title', 'vote_average', 'popularity']].head(top_n)

"""**Displaying Genre-Based Recommendation Output**"""

def recommend_by_genre(genre, top_n=5):

    filtered = movies_data[
        movies_data['genres_clean'].apply(
            lambda x: genre in x
        )
    ]

    filtered = filtered.sort_values(
        by=['vote_average', 'popularity'],
        ascending=False
    )

    return filtered[['title', 'genres_clean', 'vote_average', 'popularity']].head(top_n)

recommend_by_genre("History")

recommend_by_genre("Adventure")

recommend_by_genre("Fantasy")

recommend_by_genre("Romance")

import pickle

pickle.dump(movies_data, open('movies.pkl', 'wb'))

pickle.dump(similarity, open('similarity.pkl', 'wb'))

from google.colab import files

files.download('movies.pkl')
files.download('similarity.pkl')

movies_data['genres_clean']

all_genres = sum(movies_data['genres_clean'], [])

unique_genres = sorted(set(all_genres))

print(unique_genres)

